[workspace]
resolver = "3"
members = [
    "chlorophyll-protocol",
    "chlorophyll-client",
    "sensor_server",
    "tui-client",
]
exclude = [
    "pico_2w",
    "pico_2w_matter",
    "chlorophyll-ui",
    "chlorophyll-sensor-lib",
    "ssd1680",
    "rs-matter-embassy",
    "dioxus_client",
]

[workspace.dependencies]
chlorophyll-protocol = { path = "chlorophyll-protocol" }
chlorophyll-client = { path = "chlorophyll-client" }

tokio = { version = "1", features = ["net", "rt-multi-thread", "macros", "time", "sync", "signal"] }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
color-eyre = "0.6"
anyhow = "1"
axum = { version = "0.8", features = ["http2", "tracing"] }
askama = "0.14"

# tui-client release optimizations: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
