use dioxus::prelude::*;

use crate::types::SensorSnapshot;
#[cfg(feature = "server")]
use crate::types::SensorRow;

/// Called by the WASM client every ~2 s.
/// On the server this drains UDP packets and returns the latest state.
/// On the client it becomes an HTTP POST (generated by `#[server]`).
#[server]
pub async fn get_snapshot() -> Result<SensorSnapshot, ServerFnError> {
    use std::collections::HashMap;
    use std::net::{Ipv4Addr, SocketAddr, SocketAddrV4};
    use std::sync::OnceLock;

    use chlorophyll_protocol::DataType;
    use chlorophyll_protocol::light::Light;
    use chlorophyll_protocol::temperature::Temperature;
    use chrono::Utc;
    use sensor_server::{DataEntry, MULTICAST_ADDR, PORT, REDISCOVER_TICKS, process_packets, send_discover};
    use tokio::sync::Mutex;

    struct State {
        socket: Option<tokio::net::UdpSocket>,
        known_devices: HashMap<u128, SocketAddr>,
        readings: Vec<DataEntry>,
        tick: u64,
    }

    static S: OnceLock<Mutex<State>> = OnceLock::new();
    let mtx = S.get_or_init(|| {
        Mutex::new(State {
            socket: None,
            known_devices: HashMap::new(),
            readings: Vec::new(),
            tick: 0,
        })
    });

    let mut s = mtx.lock().await;

    // Lazy socket initialisation
    if s.socket.is_none() {
        let addr = SocketAddrV4::new(Ipv4Addr::UNSPECIFIED, PORT);
        let sock = tokio::net::UdpSocket::bind(addr)
            .await
            .map_err(|e| ServerFnError::ServerError { message: e.to_string(), code: 500, details: None })?;
        sock.join_multicast_v4(MULTICAST_ADDR, Ipv4Addr::UNSPECIFIED)
            .map_err(|e| ServerFnError::ServerError { message: e.to_string(), code: 500, details: None })?;
        send_discover(&sock).await.ok();
        s.socket = Some(sock);
    }

    s.tick = s.tick.wrapping_add(1);

    if let Some(sock) = s.socket.take() {
        if s.tick % REDISCOVER_TICKS == 0 {
            send_discover(&sock).await.ok();
        }
        let mut devices = std::mem::take(&mut s.known_devices);
        let mut readings = std::mem::take(&mut s.readings);
        process_packets(&sock, &mut devices, &mut readings).await.ok();
        s.known_devices = devices;
        s.readings = readings;
        s.socket = Some(sock);
    }

    // Build snapshot
    let now = Utc::now();

    let mut seen_ids: std::collections::HashSet<u128> =
        s.readings.iter().map(|e| e.sensor_id).collect();
    seen_ids.extend(s.known_devices.keys());
    let mut sensors: Vec<SensorRow> = seen_ids
        .iter()
        .map(|&id| {
            let mut temp_f = None;
            let mut humidity_pct = None;
            let mut lux = None;
            let mut last_seen = chrono::DateTime::<Utc>::MIN_UTC;

            for entry in s.readings.iter().rev() {
                if entry.sensor_id != id {
                    continue;
                }
                if entry.timestamp > last_seen {
                    last_seen = entry.timestamp;
                }
                match &entry.data_type {
                    DataType::Temperature(t) if temp_f.is_none() => {
                        temp_f = Some(t.get_as_f());
                    }
                    DataType::RelativeHumidity(h) if humidity_pct.is_none() => {
                        humidity_pct = Some(h.percent());
                    }
                    DataType::Light(l) if lux.is_none() => {
                        lux = Some(l.get_as_lux());
                    }
                    _ => {}
                }
                if temp_f.is_some() && humidity_pct.is_some() && lux.is_some() {
                    break;
                }
            }

            SensorRow {
                id: format!("{id:016x}"),
                temp_f,
                humidity_pct,
                lux,
                age_secs: (now - last_seen).num_seconds().max(0),
            }
        })
        .collect();
    sensors.sort_by(|a, b| a.id.cmp(&b.id));

    let temp_series = s
        .readings
        .iter()
        .filter_map(|e| {
            if let DataType::Temperature(t) = &e.data_type {
                Some((e.timestamp.timestamp(), t.get_as_f()))
            } else {
                None
            }
        })
        .collect();

    let humidity_series = s
        .readings
        .iter()
        .filter_map(|e| {
            if let DataType::RelativeHumidity(h) = &e.data_type {
                Some((e.timestamp.timestamp(), h.percent()))
            } else {
                None
            }
        })
        .collect();

    let light_series = s
        .readings
        .iter()
        .filter_map(|e| {
            if let DataType::Light(l) = &e.data_type {
                Some((e.timestamp.timestamp(), l.get_as_lux()))
            } else {
                None
            }
        })
        .collect();

    Ok(SensorSnapshot { sensors, temp_series, humidity_series, light_series })
}
