[application]

[web.app]

# HTML title tag content
title = "dioxus_client"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "dev.pg3"
publisher = "pg3.dev"
icon = ["assets/icon.png"]
